[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared", features = ["bevy_support"] }
anyhow = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
bevy = { workspace = true }
bevy_simple_text_input = "0.12"
crossbeam = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
opt-level = "s"
strip = "debuginfo"
